"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
APP_NAME = 'NonMouse'
DATA_FILES = [
    'venv/lib/python3.7/site-packages/mediapipe/python/solutions/__pycache__/hands.cpython-37.pyc',
    'venv/lib/python3.7/site-packages/mediapipe/python/__pycache__/solution_base.cpython-37.pyc'
]
OPTIONS = {
    'argv_emulation': True,
    'includes':['cv2', 'mediapipe','numpy','time','tkinter','pynput.mouse'],
	'iconfile': 'icon.ico',
	'plist': {
		'CFBundleName': APP_NAME,
		'CFBundleDisplayName': APP_NAME,
		'CFBundleGetInfoString': APP_NAME,
		'CFBundleVersion': "1.0",
		'CFBundleShortVersionString': "1.0",
		'NSHumanReadableCopyright': "Copyright (C) 2020, Yuki Takeyama, All Rights Reserved"
	}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
